# This is a basic workflow to help you get started with Actions

name: Linter

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "lint"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Set up Node.js and cache the dependencies
      - name: Setup a Node.js environment
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
      
      # Install node_modules
      - name: Install modules
        run: npm install

      # Runs code linter
      - name: Run ESLint
        run: npm run lint
      
      # Fix any possible fix
      - name: Fix any linting error
        run: npm run lint:fix
